### PR TITLE
Checkpoint 8 Private wikis

### PR DESCRIPTION
**Pull request by kthomz34**
Downgrading account from premium to standard makes all wikis belonging to current_user public

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@kthomz34 are you having issues with the ChargesControllerSpec? I'm happy to help if yes.

**Comment by kthomz34** [comment]
i added the line `post charges/new` to config/routes.rb because i got an error saying no matching route but  I thought it was working without it before I had to add that line.

**Comment by brittanyjspringer** [comment]
You're right, we need: 

    resources :charges, only: [:new, :create]

as well as the downgrade path. All 3 of these need to be tested. What will make it easier is using the stripe-mock gem => https://github.com/rebelidealist/stripe-ruby-mock

We can tackle this tonight together, if you'd like. @kthomz34

**Comment by kthomz34** [comment]
Sounds good to me!

**Comment by brittanyjspringer** [comment]
@kthomz34 I see the test changes got committed. Merging through! 🚀

**Review by brittanyjspringer — APPROVED** [review]

**Pull request merged**
