### PR TITLE
Checkpoint 4 Wiki CRUD complete

### PR DESCRIPTION
**Pull request by kthomz34**
Users is able to create a wiki and make it public.

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@kthomz34 what is your current test coverage when you run Rspec locally?

**Comment by kthomz34** [comment]
95.16% covered locally

**Comment by brittanyjspringer** [comment]
Excellent. Merged!

popkey

**Review by brittanyjspringer — APPROVED** [review]

**Comment by kthomz34** [comment]
amazing gif lol

**Pull request merged**
